version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-payment
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data:/var/lib/postgresql/data
